app/Applications/Backend/Http/routes.php
<?php

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('backend::home.welcome');
});

Route::resource('doctors', 'DoctorsController');
Route::resource('patients', 'PatientsController');
Route::resource('schedules', 'SchedulesController');

app/Applications/Backend/Http/Controllers/DoctorsController.php
<?php

namespace App\Applications\Backend\Http\Controllers;

use App\Core\Http\Controllers\Controller;
use App\Domains\Doctor\Commands\CreateNewDoctorCommand;
use App\Domains\Doctor\Commands\UpdateDoctorByIdCommand;
use App\Domains\Doctor\Contracts\DoctorRepositoryInterface;
use App\Support\Command\CommandException;
use Illuminate\Http\Request;

class DoctorsController extends Controller
{
    /**
     * DoctorsController constructor.
     */
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Show all doctors.
     *
     * @param DoctorRepositoryInterface $doctorRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(DoctorRepositoryInterface $doctorRepository)
    {
        $doctors = $doctorRepository->getAll('id', 'desc');
        $total = $doctors->total();

        return view('backend::doctors.index', compact('doctors', 'total'));
    }

    /**
     * Show doctor create form.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $doctor = null;
        $action = 'create';
        return view('backend::doctors.form', compact('doctor', 'action'));
    }

    /**
     * Store a new doctor.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            $command = new CreateNewDoctorCommand($request->all());
            $command->handle();
        } catch (CommandException $commandException) {
            return redirect()->back()->with('errors', $commandException->getError())->withInput();
        }

        return redirect()->route('backend.doctors.index')->with('success', 'Doctor created with success.');
    }

    /**
     * Edit a doctor.
     *
     * @param DoctorRepositoryInterface $doctorRepository
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(DoctorRepositoryInterface $doctorRepository, $id)
    {
        $action = 'edit';
        $doctor = $doctorRepository->findDoctorById($id);

        return view('backend::doctors.form', compact('action', 'doctor'));
    }

    /**
     * Store a new doctor.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            $command = new UpdateDoctorByIdCommand($id, $request->all());
            $command->handle();
        } catch (CommandException $commandException) {
            return redirect()->back()->with('errors', $commandException->getError())->withInput();
        }

        return redirect()->route('backend.doctors.index')->with('success', 'Doctor updated with success.');
    }

    /**
     * Destroy a doctor.
     *
     * @param DoctorRepositoryInterface $doctorRepository
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(DoctorRepositoryInterface $doctorRepository, $id)
    {
        $doctorRepository->deleteDoctorById($id);
        return redirect()->route('backend.doctors.index')->with('success', 'Doctor deleted with success.');
    }
}

app/Applications/Backend/resources/views/doctors/form.blade.php
@extends('backend::layouts.app')

<?php
    $method = 'POST';
    $formAction = route('backend.doctors.store');

    if ($action=='edit') {
        $method = 'PUT';
        $formAction = route('backend.doctors.update', $doctor->id);
    }

    $formOptions = [
        'id' => 'edit-form',
        'url' => $formAction,
        'method' => $method
    ];
?>

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {!! Form::model($doctor, $formOptions) !!}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1>Doctor</h1>
                        </div>

                        <div class="panel-body">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="row">
                                    <div class="col-md-6">
                                        {!! Form::text('name', 'Name', null, ['required']) !!}
                                    </div>

                                    <div class="col-md-6">
                                        {!! Form::email('email', 'E-mail', null, ['required']) !!}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        {!! Form::number('cpf', 'CPF', null, ['required', 'placeholder' => 'numbers only']) !!}
                                    </div>

                                    <div class="col-md-4">
                                        {!! Form::text('crm', 'CRM', null, ['required']) !!}
                                    </div>

                                    <div class="col-md-4">
                                        {!! Form::text('specialty', 'Specialty') !!}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="panel-footer">
                            <button class="btn btn-success">{{ $action=='edit' ? 'Update' : 'Create' }}</button>
                            <a href="{{ route('backend.doctors.index') }}" class="btn">cancel</a>
                        </div>

                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

app/Applications/Backend/resources/views/doctors/index.blade.php
@extends('backend::layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1>Doctors <small>({{ $total }})</small></h1>
                        <span class="pull-right actions">
                            <a href="{{ route('backend.doctors.create') }}" class="btn btn-lg btn-success">new</a>
                        </span>
                    </div>

                    <div class="panel-body">
                        <form method="POST" id="list">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="DELETE">

                            <table class="table">
                                <thead>
                                    <tr>
                                        <th style="width: 10%">#</th>
                                        <th>Doctor</th>
                                        <th style="width: 15%">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($doctors as $doctor)
                                        <tr>
                                            <td>{{ $doctor->id }}</td>
                                            <td><a href="{{ route('backend.doctors.edit', $doctor->id) }}">{{ $doctor->name }}</a></td>
                                            <td>
                                                <a href="{{ route('backend.doctors.edit', $doctor->id) }}" class="btn btn-sm btn-default">edit</a>
                                                <a href="{{ route('backend.doctors.destroy', $doctor->id) }}" title="{{ $doctor->name }}" class="delete btn btn-sm btn-danger">delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </form>

                        <div class="text-center">
                            {{ $doctors->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection