app/Applications/Backend/Http/routes.php
<?php

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('backend::home.welcome');
});

Route::resource('doctors', 'DoctorsController');
Route::resource('patients', 'PatientsController');
Route::resource('schedules', 'SchedulesController');

app/Applications/Backend/Http/Controllers/SchedulesController.php
<?php

namespace App\Applications\Backend\Http\Controllers;

use App\Core\Http\Controllers\Controller;
use App\Domains\Doctor\Contracts\DoctorRepositoryInterface;
use App\Domains\Doctor\DbDoctorRepository;
use App\Domains\Doctor\Doctor;
use App\Domains\Patient\Contracts\PatientRepositoryInterface;
use App\Domains\Patient\DbPatientRepository;
use App\Domains\Patient\Patient;
use App\Domains\Schedule\Commands\CreateNewScheduleCommand;
use App\Domains\Schedule\Commands\UpdateScheduleByIdCommand;
use App\Domains\Schedule\Contracts\ScheduleRepositoryInterface;
use App\Domains\Schedule\DbScheduleRepository;
use App\Domains\Schedule\Schedule;
use App\Support\Command\CommandException;
use Illuminate\Http\Request;

class SchedulesController extends Controller
{
    /**
     * @var PatientRepositoryInterface
     */
    private $patientRepository;
    /**
     * @var DoctorRepositoryInterface
     */
    private $doctorRepository;

    /**
     * SchedulesController constructor.
     * @param PatientRepositoryInterface $patientRepository
     * @param DoctorRepositoryInterface $doctorRepository
     */
    public function __construct(
        PatientRepositoryInterface $patientRepository,
        DoctorRepositoryInterface $doctorRepository)
    {
        $this->middleware(['auth']);
        $this->patientRepository = $patientRepository;
        $this->doctorRepository = $doctorRepository;
    }

    /**
     * @return \Illuminate\Support\Collection
     */
    private function doctors()
    {
        return $this->doctorRepository->getAllPluckedUp();
    }

    /**
     * @return \Illuminate\Support\Collection
     */
    private function patients()
    {
        return $this->patientRepository->getAllPluckedUp();
    }

    /**
     * @return array
     */
    private function availableStatus()
    {
        return Schedule::$arrStatusForHumans;
    }

    /**
     * Show all schedules.
     *
     * @param ScheduleRepositoryInterface $scheduleRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(ScheduleRepositoryInterface $scheduleRepository)
    {
        $schedules = $scheduleRepository->getAll('schedules.id', 'desc');
        $total = $schedules->total();

        return view('backend::schedules.index', compact('schedules', 'total')
        );
    }

    /**
     * Show schedule create form.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $schedule = null;
        $action = 'create';
        $patients = $this->patients();
        $doctors = $this->doctors();
        $availableStatus = $this->availableStatus();

        return view(
            'backend::schedules.form',
            compact('schedule', 'action', 'patients', 'doctors', 'availableStatus')
        );
    }

    /**
     * Store a new schedule.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            $command = new CreateNewScheduleCommand($request->all());
            $command->handle();
        } catch (CommandException $commandException) {
            return redirect()->back()->with('errors', $commandException->getError())->withInput();
        }

        return redirect()->route('backend.schedules.index')->with('success', 'Schedule created with success.');
    }

    /**
     * Edit a schedule.
     *
     * @param ScheduleRepositoryInterface $scheduleRepository
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(ScheduleRepositoryInterface $scheduleRepository, $id)
    {
        $action = 'edit';
        $schedule = $scheduleRepository->findScheduleById($id);

        $patients = $this->patients();
        $doctors = $this->doctors();
        $availableStatus = $this->availableStatus();

        return view(
            'backend::schedules.form',
            compact('schedule', 'action', 'patients', 'doctors', 'availableStatus')
        );
    }

    /**
     * Store a new schedule.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            $command = new UpdateScheduleByIdCommand($id, $request->all());
            $command->handle();
        } catch (CommandException $commandException) {
            return redirect()->back()->with('errors', $commandException->getError())->withInput();
        }

        return redirect()->route('backend.schedules.index')->with('success', 'Schedule updated with success.');
    }

    /**
     * Destroy a schedule.
     *
     * @param ScheduleRepositoryInterface $scheduleRepository
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(ScheduleRepositoryInterface $scheduleRepository, $id)
    {
        $scheduleRepository->deleteScheduleById($id);
        return redirect()->route('backend.schedules.index')->with('success', 'Schedule deleted with success.');
    }
}

app/Applications/Backend/resources/views/schedules/form.blade.php
@extends('backend::layouts.app')

<?php
    $method = 'POST';
    $formAction = route('backend.schedules.store');
    $date = null;
    $hour = null;

    if ($action=='edit') {
        $method = 'PUT';
        $formAction = route('backend.schedules.update', $schedule->id);
        $date = $schedule->date->format('d/m/Y');
        $hour = $schedule->date->format('H:i');
    }

    $formOptions = [
        'id' => 'edit-form',
        'url' => $formAction,
        'method' => $method
    ];
?>

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {!! Form::model($schedule, $formOptions) !!}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1>Schedule</h1>
                        </div>

                        <div class="panel-body">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="row">
                                    <div class="col-md-3">
                                        {!! Form::select('status', 'Status', $availableStatus, null, ['required']) !!}
                                    </div>
                                    <div class="col-md-offset-3 col-md-3">
                                        {!! Form::text('date', 'Date', $date, ['required', 'placeholder' => 'dd/mm/yyyy']) !!}
                                    </div>
                                    <div class="col-md-3">
                                        {!! Form::text('hour', 'Hour', $hour, ['required', 'placeholder' => 'hh:mm']) !!}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        {!! Form::select('patient_id', 'Patient', $patients, null, ['required']) !!}
                                    </div>

                                    <div class="col-md-6">
                                        {!! Form::select('doctor_id', 'Doctor', $doctors, null, ['required']) !!}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        {!! Form::textarea('message', 'Message') !!}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="panel-footer">
                            <button class="btn btn-success">{{ $action=='edit' ? 'Update' : 'Create' }}</button>
                            <a href="{{ route('backend.schedules.index') }}" class="btn">cancel</a>
                        </div>

                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

app/Applications/Backend/resources/views/schedules/index.blade.php
@extends('backend::layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1>Schedules <small>({{ $total }})</small></h1>
                        <span class="pull-right actions">
                            <a href="{{ route('backend.schedules.create') }}" class="btn btn-lg btn-success">new</a>
                        </span>
                    </div>

                    <div class="panel-body">
                        <form method="POST" id="list">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="DELETE">

                            <table class="table">
                                <thead>
                                    <tr>
                                        <th style="width: 10%">#</th>
                                        <th>Doctor</th>
                                        <th>Patient</th>
                                        <th>When</th>
                                        <th style="width: 15%">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($schedules as $schedule)
                                        <tr>
                                            <td>{{ $schedule->id }}</td>
                                            <td><a href="{{ route('backend.schedules.edit', $schedule->id) }}">{{ $schedule->doctor_name }}</a></td>
                                            <td><a href="{{ route('backend.schedules.edit', $schedule->id) }}">{{ $schedule->patient_name }}</a></td>
                                            <td><a href="{{ route('backend.schedules.edit', $schedule->id) }}">{{ $schedule->date->format('d/m/Y') }} at {{ $schedule->date->format('H:i') }}</a></td>
                                            <td>
                                                <a href="{{ route('backend.schedules.edit', $schedule->id) }}" class="btn btn-sm btn-default">edit</a>
                                                <a href="{{ route('backend.schedules.destroy', $schedule->id) }}"
                                                   title="Schedule of patient {{ $schedule->patient_name }} with doctor {{ $schedule->doctor_name }}"
                                                   class="delete btn btn-sm btn-danger">delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </form>

                        <div class="text-center">
                            {{ $schedules->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection