app/Applications/Backend/Http/routes.php
<?php

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('backend::home.welcome');
});

Route::resource('doctors', 'DoctorsController');
Route::resource('patients', 'PatientsController');
Route::resource('schedules', 'SchedulesController');

app/Applications/Backend/Http/Controllers/PatientsController.php
<?php

namespace App\Applications\Backend\Http\Controllers;

use App\Core\Http\Controllers\Controller;
use App\Domains\Patient\Commands\CreateNewPatientCommand;
use App\Domains\Patient\Commands\UpdatePatientByIdCommand;
use App\Domains\Patient\Contracts\PatientRepositoryInterface;
use App\Support\Command\CommandException;
use Illuminate\Http\Request;

class PatientsController extends Controller
{
    /**
     * PatientsController constructor.
     */
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Show all patients.
     *
     * @param PatientRepositoryInterface $patientRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(PatientRepositoryInterface $patientRepository)
    {
        $patients = $patientRepository->getAll('id', 'desc');
        $total = $patients->total();

        return view('backend::patients.index', compact('patients', 'total'));
    }

    /**
     * Show patient create form.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $patient = null;
        $action = 'create';
        return view('backend::patients.form', compact('patient', 'action'));
    }

    /**
     * Store a new patient.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            $command = new CreateNewPatientCommand($request->all());
            $command->handle();
        } catch (CommandException $commandException) {
            return redirect()->back()->with('errors', $commandException->getError())->withInput();
        }

        return redirect()->route('backend.patients.index')->with('success', 'Patient created with success.');
    }

    /**
     * Edit a patient.
     *
     * @param PatientRepositoryInterface $patientRepository
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(PatientRepositoryInterface $patientRepository, $id)
    {
        $action = 'edit';
        $patient = $patientRepository->findPatientById($id);

        return view('backend::patients.form', compact('action', 'patient'));
    }

    /**
     * Store a new patient.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            $command = new UpdatePatientByIdCommand($id, $request->all());
            $command->handle();
        } catch (CommandException $commandException) {
            return redirect()->back()->with('errors', $commandException->getError())->withInput();
        }

        return redirect()->route('backend.patients.index')->with('success', 'Patient updated with success.');
    }

    /**
     * Destroy a patient.
     *
     * @param PatientRepositoryInterface $patientRepository
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(PatientRepositoryInterface $patientRepository, $id)
    {
        $patientRepository->deletePatientById($id);
        return redirect()->route('backend.patients.index')->with('success', 'Patient deleted with success.');
    }
}

app/Applications/Backend/resources/views/patients/form.blade.php
@extends('backend::layouts.app')

<?php
    $method = 'POST';
    $formAction = route('backend.patients.store');

    if ($action=='edit') {
        $method = 'PUT';
        $formAction = route('backend.patients.update', $patient->id);
    }

    $formOptions = [
        'id' => 'edit-form',
        'url' => $formAction,
        'method' => $method
    ];
?>

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {!! Form::model($patient, $formOptions) !!}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1>Patient</h1>
                        </div>

                        <div class="panel-body">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="row">
                                    <div class="col-md-6">
                                        {!! Form::text('name', 'Name', null, ['required']) !!}
                                    </div>

                                    <div class="col-md-6">
                                        {!! Form::email('email', 'E-mail', null, ['required']) !!}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        {!! Form::number('cpf', 'CPF', null, ['required', 'placeholder' => 'numbers only']) !!}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="panel-footer">
                            <button class="btn btn-success">{{ $action=='edit' ? 'Update' : 'Create' }}</button>
                            <a href="{{ route('backend.patients.index') }}" class="btn">cancel</a>
                        </div>

                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

app/Applications/Backend/resources/views/patients/index.blade.php
@extends('backend::layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1>Patients <small>({{ $total }})</small></h1>
                        <span class="pull-right actions">
                            <a href="{{ route('backend.patients.create') }}" class="btn btn-lg btn-success">new</a>
                        </span>
                    </div>

                    <div class="panel-body">
                        <form method="POST" id="list">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="DELETE">

                            <table class="table">
                                <thead>
                                    <tr>
                                        <th style="width: 10%">#</th>
                                        <th>Patient</th>
                                        <th style="width: 15%">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($patients as $patient)
                                        <tr>
                                            <td>{{ $patient->id }}</td>
                                            <td><a href="{{ route('backend.patients.edit', $patient->id) }}">{{ $patient->name }}</a></td>
                                            <td>
                                                <a href="{{ route('backend.patients.edit', $patient->id) }}" class="btn btn-sm btn-default">edit</a>
                                                <a href="{{ route('backend.patients.destroy', $patient->id) }}" title="{{ $patient->name }}" class="delete btn btn-sm btn-danger">delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </form>

                        <div class="text-center">
                            {{ $patients->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection